### ISSUE TITLE
RuntimeError redirection forbidden

### ISSUE THREAD

**Issue by szydloit** [DannyBen/snapcrawl#16]
Hello,
running command
`docker-compose run snapcrawl go https://thissite.com -d 10 --only "^((?!pdfc/112).)*$"`

![image](https://user-images.githubusercontent.com/54842471/64624711-5c403d80-d3eb-11e9-9ec5-9b844b4c1c7e.png)

**Comment by DannyBen** [comment]
The fact that it extracts links even from skipped pages is by design I believe. Skip means "do not take a screenshot".

The redirection error I am not sure what's going on - I can only debug what I can reproduce, so if you see a different site that behaves the same, or if you can share the URL + the quickest command possible to reproduce the issue (i.e. without waiting for depth 10), I will take a look.

**Comment by DannyBen** [comment]
I found the problem. It is caused by protocol downgrade redirects (HTTPS to HTTP) which is prevented in `open-uri`. I will see if I can either fix it, or switch to using another web client.

**Comment by DannyBen** [comment]
Thanks for the information you provided - the site you gave me provided plenty of issues to fix. I will deploy a fix release shortly and docker container shortly.

**Comment by DannyBen** [comment]
Ok - version 0.3.0 is released on RubyGems and on DockerHub.
Since you are using the docker version, you should run:

```
$ docker pull dannyben/snapcrawl
$ docker run --rm -it dannyben/snapcrawl --version
0.3.0
```
