### ISSUE TITLE
Try catch error instead of stopping script

### ISSUE THREAD

**Issue by szydloit** [DannyBen/snapcrawl#19]
Hello, 
maybe there's option to catch error / igonre url if it's not valid, instead of stopping script . Here's example when somebody put utf letter for mistake:

![image](https://user-images.githubusercontent.com/54842471/64676890-d1a52000-d476-11e9-90fc-1795f5c9f260.png)

URI::InvalidURIError
URI must be ascii only "https://www.obowi\u0105zki-informacyjne.pl/"

**Comment by DannyBen** [comment]
That is an easy fix. Will work on it later today.

**Comment by DannyBen** [comment]
Ok. I have added some handling of unicode URLs, + catching some exceptions.
Since I do not want to catch ALL exceptions, some errors might still occur in cases that we haven't encountered yet. When they do, we will adjust the rescue blocks.

Version 0.3.1 is live on RubyGems and the docker image is being built right now and should be ready soon.
