### ISSUE TITLE
ArgumentError - unnumbered(1) mixed with named

### ISSUE THREAD

**Issue by nicholas-gh** [DannyBen/snapcrawl#33]
This looks ideal to help me create a page by page analysis/review of a website, many thanks for it!

It stops after a few pages for me, with this output:
```
ArgumentError
unnumbered(1) mixed with named
```

`log_level=0` doesn't add any more info on the fault. Does it look familiar? I've grepped the source for `unnumbered`, but no hits, so it probably is in some dependency... 

I can email you a link to the site that causes the fault, if it might be an HTML parsing issue.

**Comment by DannyBen** [comment]
I suspect some URL issue rather than HTML parsing issue.
Yes, I will need the URL in order to reproduce. Possibly, the URL that is closest to the error so I wont need to crawl for long before reaching it.

**Comment by DannyBen** [comment]
Well - thanks for emailing the additional details.

I found the problem, and to be honest, I knew this implementation will come back to punch me in the face.

The problem is here:

https://github.com/DannyBen/snapcrawl/blob/3f06243d1bcf108a140d3292b199fa8bc2aa4ebb/lib/snapcrawl/log_helpers.rb#L15

This line pretty-prints the log message, while converting things like `%{green}` and `%{bold}` to their respective terminal ansi code. In case where the message contains an unescaped `%` sign, Ruby complains. In our case, it simply reaches a URL with a percent sign.

I need to think how to best fix it, or preferably, avoid it by refactoring the pretty-logging.

In any case - I believe I can fix it tomorrow.

**Comment by DannyBen** [comment]
Version 0.5.2 was released to RubyGems with the fix, as well as a docker image.

As I understand you are using the docker image, ensure you have the last version with

```
$ docker pull dannyben/snapcrawl
$ docker run --rm -it dannyben/snapcrawl --version
0.5.2
```
