### ISSUE TITLE
Screenshots not saving to default snaps folder on Windows machine

### ISSUE THREAD

**Issue by sunithaparuchuri** [DannyBen/snapcrawl#6]
DannyBen,
I am able to install snapcrawl on Windows 7 and Windows 10 machines successfully. 
When trying to screenshots website. It is saying 
Visit: http://uown.co 
Snap! snapping picture....
returning back to c:\ 
when I go back to c:\snaps folder -- found empty folder. Can you please help me on this..

**Comment by DannyBen** [comment]
Do you have ImageMagick installed?
Try running `convert -version` - if it works, you do, if not - you need to install it.

If this is indeed the problem, I will fix snapcrawl to report when it is not installed, so it will be clear in the future.

**Comment by sunithaparuchuri** [comment]
Hi DannyBen,

Thank you for your reply. We are able to Install ImageMagick-6.7.2-7 Version. Started working. If you upgrade code to the latest ImageMagick, it is more helpful. But we are good at this point. 
Thank you so much.

**Comment by sunithaparuchuri** [comment]
Hi DannyBen

Yes I installed older version. Started working 
Thank you for response 

Thanks
Sunitha

**Comment by DannyBen** [comment]
I am not sure what you mean by "If you upgrade code to the latest ImageMagick" - snapcrawl does not install ImageMagick or PhantomJS - which are both needed for it to work.

What I want to do, is at least:

1. Mention these prerequisites in the README
2. Show a clear error when ImageMagick is not installed, so people will know what to do.

I will deploy a version soon (but you don't need to worry about downloading it, since the functionality is the same other than these two points above).
