### ISSUE TITLE
Puppeteer or Selenium/WebDriver instead of Phantom.js?

### ISSUE THREAD

**Issue by lol768** [DannyBen/snapcrawl#8]
AIUI PhantomJS is [kinda dead](https://github.com/ariya/phantomjs/issues/15105), it'd be nice to see a project like this support Puppeteer w/ Chrome Headless/Firefox

See also https://github.com/GoogleChrome/puppeteer/tree/master/experimental/puppeteer-firefox

**Comment by DannyBen** [comment]
Yes, I know it is very much dead.

Snapcrawl does not even use PhantomJS directly. The snapshot capability is provided by the [Webshot gem][1], which uses PhantomJS.

The whole idea was to provide some easy CLI with ninimal dependencies (back then, we could install PhantomJS using a gem, so all you really needed is ImageMagick).

It does not make sense for me to have a Ruby gem that needs a Node package in order to run.

If you have some suggestions on how to use it without forcing the user to deal with Node dependencies, or any other way to grab site screenshots natively in Ruby, I am open to any change that will replace PhantomJS.

[1]: https://github.com/vitalie/webshot

**Comment by lol768** [comment]
Hey @DannyBen,

Thanks for the prompt response and for explaining the context around the gem you're using. I agree it's a bit of a pain to depend on a Node package.

>If you have some suggestions on how to use it without forcing the user to deal with Node dependencies, or any other way to grab site screenshots natively in Ruby, I am open to any change that will replace PhantomJS.

I think Puppeteer, under the hood, uses CDP so presumably all the functionality is available via that interface. Therefore I think using the Devtools Protocol directly (using e.g. Capybara and a driver) is the way to go - Apparition looks promising in this regard thoug,h I'm not much of a Ruby person and haven't got any experience with it myself.

I'm not sure how important x-browser support is to you, but I think Firefox implements most of the CDP interface too so whether Apparition would just work directly I'm unsure :man_shrugging: . There's presumably other Capybara drivers that would support `page.save_screenshot` and work with different browsers. Maybe it could be configurable.

**Comment by DannyBen** [comment]
From experience, I can tell you that the Capybara drivers configuration and dependences consumed a lot of time and effort from me - not in regards to Snapcrawl, but rather in a more conventional Ruby testing context. I do not think the user should need to choose a driver. We should have a good driver that is doing a good job at taking a screenshot, and be done with it in my mind.

I might take a look into it a little later down the week, to see if such a change is both easy and worthwhile.

**Comment by DannyBen** [comment]
After a little bit of reading, I understand that other solutions actually require you to have one version or another of Chrome to be installed in order to operate, which deepens the dependency mess, especially when one desires a simple, friction-less headless solution.

The bottom line is that at this time, I do not see any other almost-standalone solution, such as PhantomJS was.

I will leave the issue open for now, perhaps someone or some *thing* will come up in the near future.

For the time being, I have published a [Snapcrawl Docker Image](https://github.com/DannyBen/docker-snapcrawl), which makes it usable out of the box on any system with docker.
